export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const ADD_COMMENT = 'ADD_COMMENT'

export const LOAD_ALL_ARTICLES_START = 'LOAD_ALL_ARTICLES_START'
export const LOAD_ALL_ARTICLES_SUCCESS = 'LOAD_ALL_ARTICLES_SUCCESS'
export const LOAD_ALL_ARICLES_FAIL = 'LOAD_ALL_ARICLES_FAIL'
